export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_ORDER_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_ORDER_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_ORDER_FAIL';
export const ORDER_PAY_RESET = 'ORDER_ORDER_RESET';
